version: "3.9"

services:

  db:
    image: db
    build:
      context: ./database/postgres/
      target: db
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - net
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    expose:
      - "8081"
    networks:
      - net

networks:
  net:

volumes:
  db: