version: "3.8"

services:

  db:
    image: db
    build:
      context: ./database/postgres/
      target: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=idp,blog
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - net
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 3

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    expose:
      - "8081"
    networks:
      - net

  server:
    image: blog-server
    build:
      context: ./
    ports:
      - "8888:8888"
    expose:
      - "8888"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net
    volumes:
      - server:/home/node/app

  idp:
    image: idp
    build:
      context: ./idp/
      target: idp
    command:
      - start-dev
    environment:
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_DATABASE: idp
      DB_USER: idp
      DB_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net
    ports:
      - "8080:8080"
      - "8443:8443"
    expose:
      - "8080"
      - "8443"

networks:
  net:

volumes:
  db:
  server:
